//! Control SAB layout — single source of truth for the main↔worker SAB
//! transport. Both languages read these offsets/sizes verbatim; the TS mirror
//! is generated by `cargo run --bin gen-bindings` into
//! `web/src/generated/control-sab.ts`.
//!
//! Layout (one shared buffer, total = `CONTROL_SAB_BYTES`):
//!
//! ```text
//!   i32 region   bytes [0, 1024)
//!     Fixed-width control + status fields, indexed in i32 slots.
//!   inspect-response bytes [INSPECT_RESP_OFFSET, INSPECT_RESP_OFFSET + INSPECT_RESP_CAP)
//!   profile-report  bytes [PROFILE_REPORT_OFFSET, PROFILE_REPORT_OFFSET + PROFILE_REPORT_CAP)
//!   nn-stats        bytes [NN_STATS_OFFSET,       NN_STATS_OFFSET       + NN_STATS_CAP)
//! ```
//!
//! Numeric fields use `Atomics.load` / `Atomics.store` on an Int32Array view.
//! `f32` values are carried as `f32::to_bits` (`Float32` ↔ `Int32` bit-cast,
//! same trick the snapshot header already uses for `tps`).
//!
//! Variable-length buffers (inspect response, profile report, NN stats) are
//! length-prefixed via their epoch + len i32 slots and a fixed-capacity byte
//! window. Producers advance the epoch *after* writing the bytes; consumers
//! read the epoch first, then the bytes, then re-check the epoch to detect
//! mid-write races.

use crate::wasm_api::SLIDER_COUNT;

// ─── i32 slot indices ───────────────────────────────────────────────────────
//
// Each constant names a 4-byte-aligned slot in the leading i32 region. Keep
// indices stable: the TS mirror copies them verbatim.

/// Snapshot double-buffer: active slot index (0 or 1).
pub const CTRL_CURRENT_SLOT: usize = 0;
/// Snapshot publication counter; incremented after every slot flip.
pub const CTRL_SEQ: usize = 1;
/// Futex word the worker `Atomics.wait`s on while paused. Main bumps + notifies
/// to wake. (Wave D's `Atomics.waitAsync` usage is gone in v1.10.)
pub const CTRL_FUTEX: usize = 2;
/// Pause flag (0 = running, 1 = paused). Atomic.
pub const CTRL_PAUSED: usize = 3;
/// Target ticks-per-second, carried as `f32::to_bits`.
pub const CTRL_TARGET_TPS_BITS: usize = 4;
/// Monotone counter bumped whenever main writes any slider value. Worker reads
/// once per tick; if unchanged, skip the whole slider re-read.
pub const CTRL_CONTROL_EPOCH: usize = 5;
/// Bumped by main to request `profile_clear()`. Worker compares to its last
/// observed value and runs the clear on advance.
pub const CTRL_PROFILE_CLEAR_EPOCH: usize = 6;
/// Bumped by main to request `reset_jank()`. Worker compares + acts on advance.
pub const CTRL_RESET_JANK_EPOCH: usize = 7;
/// Profiler rolling-window length, in milliseconds (u32). Main writes the
/// desired window; the worker reads it every tick and applies it to the
/// Rust profiler via `world.profile_set_window_ms(...)`. A value of 0 is
/// treated as "leave unchanged" so an uninitialized SAB doesn't zero out
/// the panel mid-boot.
pub const CTRL_PROFILE_WINDOW_MS: usize = 8;

/// First slider slot. Slots `[CTRL_SLIDERS_BASE, CTRL_SLIDERS_BASE + SLIDER_COUNT)`
/// hold one f32-bits value per slider in canonical order (see `SLIDER_NAMES`).
/// v2.0 Wave 2a: SLIDER_COUNT bumped to 48 (24 scalar + 24 mutation-bucket
/// slots); the inspector request block was shifted up from 64 to 80 to keep a
/// safe gap above the slider region (16 + 48 = 64 must stay below the req block).
pub const CTRL_SLIDERS_BASE: usize = 16;

/// Inspector request block: epoch + kind + 3 f32 params + 2 u32 id halves.
pub const CTRL_INSPECT_REQ_EPOCH: usize = 80;
/// 0 = inspect by world coord (uses wx/wy/tol), 1 = inspect by stable id.
pub const CTRL_INSPECT_REQ_KIND: usize = 81;
/// World-x for `inspect_at`, f32-bits.
pub const CTRL_INSPECT_REQ_WX_BITS: usize = 82;
/// World-y for `inspect_at`, f32-bits.
pub const CTRL_INSPECT_REQ_WY_BITS: usize = 83;
/// Tolerance world-radius for `inspect_at`, f32-bits.
pub const CTRL_INSPECT_REQ_TOL_BITS: usize = 84;
/// Lower 32 bits of the stable id for `inspect_id`.
pub const CTRL_INSPECT_REQ_ID_LO: usize = 85;
/// Upper 32 bits of the stable id for `inspect_id`.
pub const CTRL_INSPECT_REQ_ID_HI: usize = 86;

/// Inspector response epoch, bumped after the response bytes are written.
pub const CTRL_INSPECT_RESP_EPOCH: usize = 88;
/// Length of the inspector response JSON in bytes (0 = not-found).
pub const CTRL_INSPECT_RESP_LEN: usize = 89;
/// Echo of the request epoch the response is answering (so main can
/// correlate if it sent multiple requests before draining).
pub const CTRL_INSPECT_RESP_REQ_EPOCH: usize = 90;

/// Profile report response: epoch bumped after the bytes are written.
pub const CTRL_PROFILE_REPORT_EPOCH: usize = 96;
/// Length of the profile report JSON in bytes.
pub const CTRL_PROFILE_REPORT_LEN: usize = 97;

/// NN stats response: epoch bumped after the bytes are written.
pub const CTRL_NN_STATS_EPOCH: usize = 104;
/// Length of the NN stats JSON in bytes.
pub const CTRL_NN_STATS_LEN: usize = 105;

/// v2.0 Wave 4: polled species-table report (species_id → {color, name, count}).
/// Cadence-written by the worker (mirrors the NN-stats epoch/len pattern — no
/// request side); epoch bumped after the bytes are written. The Monitor
/// pop-graph + canvas color table consume this (consumer lands in Wave 5).
pub const CTRL_SPECIES_TABLE_EPOCH: usize = 112;
/// Length of the species-table JSON in bytes.
pub const CTRL_SPECIES_TABLE_LEN: usize = 113;

/// v2.0.3 Stream 2b: camera lane — world-space center X, carried as f32::to_bits.
/// Main writes each RAF; worker reads in write_snapshot to compute the clipmap window.
pub const CTRL_CAMERA_CX_BITS: usize = 120;
/// v2.0.3 Stream 2b: camera lane — world-space center Y, carried as f32::to_bits.
pub const CTRL_CAMERA_CY_BITS: usize = 121;
/// v2.0.3 Stream 2b: camera lane — zoom (px/world-unit), carried as f32::to_bits.
pub const CTRL_CAMERA_ZOOM_BITS: usize = 122;
/// v2.0.3 Stream 2b: camera lane — viewport width in CSS pixels (u32).
pub const CTRL_CAMERA_VIEWPORT_W: usize = 123;
/// v2.0.3 Stream 2b: camera lane — viewport height in CSS pixels (u32).
pub const CTRL_CAMERA_VIEWPORT_H: usize = 124;

/// Length of the leading i32 region in i32 slots. Byte buffers start
/// at `CTRL_I32_REGION_LEN * 4`.
pub const CTRL_I32_REGION_LEN: usize = 256;

// ─── Byte-region offsets and capacities ─────────────────────────────────────

/// Byte offset of the inspector response payload.
pub const INSPECT_RESP_OFFSET: usize = CTRL_I32_REGION_LEN * 4;
/// Maximum inspector response payload size in bytes (8 KB).
pub const INSPECT_RESP_CAP: usize = 8 * 1024;

/// Byte offset of the profile-report payload.
pub const PROFILE_REPORT_OFFSET: usize = INSPECT_RESP_OFFSET + INSPECT_RESP_CAP;
/// Maximum profile-report payload size in bytes (16 KB).
pub const PROFILE_REPORT_CAP: usize = 16 * 1024;

/// Byte offset of the NN-stats payload.
pub const NN_STATS_OFFSET: usize = PROFILE_REPORT_OFFSET + PROFILE_REPORT_CAP;
/// Maximum NN-stats payload size in bytes (4 KB).
pub const NN_STATS_CAP: usize = 4 * 1024;

/// Byte offset of the v2.0 Wave 4 species-table payload.
pub const SPECIES_TABLE_OFFSET: usize = NN_STATS_OFFSET + NN_STATS_CAP;
/// Maximum species-table payload size in bytes (4 KB). At ~64 B/species
/// (id + color + name + count) this holds ~60 species — far above the v2.0
/// fixed 10 and well into v2.1 split territory. The producer clamps to this.
pub const SPECIES_TABLE_CAP: usize = 4 * 1024;

/// Total control SAB size in bytes. Includes some trailing padding so future
/// fields can be added without breaking on-disk SAB shape assumptions.
pub const CONTROL_SAB_BYTES: usize = SPECIES_TABLE_OFFSET + SPECIES_TABLE_CAP + 1024;

// ─── Compile-time sanity ────────────────────────────────────────────────────

const _: () = assert!(
    CTRL_SLIDERS_BASE + SLIDER_COUNT < CTRL_INSPECT_REQ_EPOCH,
    "slider slots must not overlap the inspector request block",
);
const _: () = assert!(
    NN_STATS_OFFSET + NN_STATS_CAP <= CONTROL_SAB_BYTES,
    "NN-stats buffer must fit within the control SAB",
);
const _: () = assert!(
    SPECIES_TABLE_OFFSET + SPECIES_TABLE_CAP <= CONTROL_SAB_BYTES,
    "species-table buffer must fit within the control SAB",
);
const _: () = assert!(
    CTRL_I32_REGION_LEN * 4 <= INSPECT_RESP_OFFSET,
    "i32 region must end before the inspect-response byte buffer starts",
);
const _: () = assert!(
    CTRL_CAMERA_VIEWPORT_H < CTRL_I32_REGION_LEN,
    "camera lanes must fit within the i32 region",
);
